In [1]:
import numpy as np

In [3]:
arr=np.array([1,2,3,4,5])

In [4]:
arr

array([1, 2, 3, 4, 5])

In [6]:
print("*"
print(arr+1)
print("--------------")
print(arr-1)
print("--------------")
print(arr*2)
print("--------------")
print(arr/2)
print("--------------")
print(arr**2)
print("--------------")
print(arr%2)

--------------
[2 3 4 5 6]
--------------
[0 1 2 3 4]
--------------
[ 2  4  6  8 10]
--------------
[0.5 1.  1.5 2.  2.5]
--------------
[ 1  4  9 16 25]
--------------
[1 0 1 0 1]


In [7]:
arr


array([1, 2, 3, 4, 5])

In [8]:
arr=np.array([1, 2, 3, 4, 5,6])


In [9]:
arr


array([1, 2, 3, 4, 5, 6])

In [10]:
arr1=arr.reshape(3,2)


In [11]:
arr1

array([[1, 2],
       [3, 4],
       [5, 6]])

In [12]:
arr

array([1, 2, 3, 4, 5, 6])

In [13]:
arr1.sum()

21

In [14]:
arr.max()

6

In [15]:
arr.min()

1

In [19]:
# max element column-wise
arr1.max(axis=0)    

array([5, 6])

In [20]:
# max element row-wise
arr1.max(axis=1)     

array([2, 4, 6])

In [21]:
# min element column-wise
arr1.min(axis=0)     

array([1, 2])

In [ ]:
# min element column-wise
arr1.min(axis=1)      