In [1]:
!pip install numpy

Defaulting to user installation because normal site-packages is not writeable


In [2]:
import numpy as np

In [3]:
np

<module 'numpy' from 'C:\\ProgramData\\anaconda3\\Lib\\site-packages\\numpy\\__init__.py'>

In [4]:
lst=[1,2,3,4,5]

[1, 2, 3, 4, 5]

In [6]:
type(lst)

list

In [58]:
zeros=np.zeros((3,4))

In [59]:
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

ValueError: cannot reshape array of size 12 into shape (2,3)

In [79]:
arr=np.random.random((5,6))

In [64]:
arr

array([[0.39966806, 0.02320804, 0.82016022],
       [0.41767997, 0.21562296, 0.98969947],
       [0.84351061, 0.73175896, 0.45502339],
       [0.30068127, 0.24612906, 0.16634352]])

In [83]:
array=np.reshape(arr,(6,5))

In [84]:
array

array([[0.56754129, 0.49723017, 0.94128554, 0.70646218, 0.73488611],
       [0.43635125, 0.84257176, 0.08052241, 0.11720042, 0.73028439],
       [0.95568328, 0.06220232, 0.00940507, 0.47611683, 0.12048493],
       [0.24772752, 0.6333887 , 0.37909774, 0.80402313, 0.33895657],
       [0.1961491 , 0.98890133, 0.74602701, 0.48079711, 0.37101716],
       [0.25251163, 0.62725008, 0.30532499, 0.36302948, 0.13393003]])

In [90]:
arr1=array.reshape((5,6))

In [91]:
arr1

array([[0.56754129, 0.49723017, 0.94128554, 0.70646218, 0.73488611,
        0.43635125],
       [0.84257176, 0.08052241, 0.11720042, 0.73028439, 0.95568328,
        0.06220232],
       [0.00940507, 0.47611683, 0.12048493, 0.24772752, 0.6333887 ,
        0.37909774],
       [0.80402313, 0.33895657, 0.1961491 , 0.98890133, 0.74602701,
        0.48079711],
       [0.37101716, 0.25251163, 0.62725008, 0.30532499, 0.36302948,
        0.13393003]])